package main

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// Report accumulates per-host, per-phase results and renders the markdown table from
// docs/LINUX-TESTING.md §4 — so the matrix in the docs is generated, not hand-maintained.
type Report struct {
	Version string
	Started time.Time
	// host name -> phase -> result
	cells map[string]map[string]Result
	facts map[string]map[string]string
	order []string
}

func NewReport(version string) *Report {
	return &Report{
		Version: version,
		Started: time.Now(),
		cells:   map[string]map[string]Result{},
		facts:   map[string]map[string]string{},
	}
}

func (r *Report) Add(phase string, res Result) {
	name := res.Host.Name
	if _, ok := r.cells[name]; !ok {
		r.cells[name] = map[string]Result{}
		r.order = append(r.order, name)
	}
	res.Phase = phase
	r.cells[name][phase] = res
}

func (r *Report) AddFacts(host string, f map[string]string) {
	r.facts[host] = f
}

func (r *Report) mark(host, phase string) string {
	res, ok := r.cells[host][phase]
	if !ok {
		return "⏳"
	}
	return res.Mark()
}

var phaseColumns = []struct{ key, title string }{
	{"deploy", "deploy"},
	{"install", "install"},
	{"p0", "P0"},
	{"p1", "P1 probe"},
}

// Markdown renders the results document.
func (r *Report) Markdown(hosts []Host) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Linux test results — ktflash %s\n\n", r.Version)
	fmt.Fprintf(&b, "Generated by `vmatrix` at %s.\n\n", r.Started.UTC().Format(time.RFC3339))
	b.WriteString("Phases and pass criteria: [`docs/LINUX-TESTING.md`](LINUX-TESTING.md) §3.\n")
	b.WriteString("**P2 (unlock) and P3 (flash) are deliberately not automated** — they change ")
	b.WriteString("device state and destroy firmware respectively, so they stay manual.\n\n")

	// --- matrix ---
	b.WriteString("## Matrix\n\n| Guest | Arch | Artifact |")
	for _, p := range phaseColumns {
		fmt.Fprintf(&b, " %s |", p.title)
	}
	b.WriteString(" P2 unlock | P3 flash | Notes |\n|---|---|---|")
	for range phaseColumns {
		b.WriteString(":--:|")
	}
	b.WriteString(":--:|:--:|---|\n")

	for _, h := range hosts {
		f := r.facts[h.Name]
		arch := h.Arch
		if arch == "" && f != nil {
			arch = f["arch"]
		}
		if arch == "" {
			arch = "?"
		}
		artifact := h.Artifact
		if artifact == "" {
			artifact = ArtifactTarball
		}
		fmt.Fprintf(&b, "| %s | %s | %s |", h.Name, arch, artifact)
		for _, p := range phaseColumns {
			fmt.Fprintf(&b, " %s |", r.mark(h.Name, p.key))
		}
		// P2/P3 are manual, so they are always ⏳ here unless a human edits the file.
		manual := "⏳"
		if !h.HasDongle {
			manual = "n/a"
		}
		fmt.Fprintf(&b, " %s | %s | %s |\n", manual, manual, r.notes(h))
	}

	// --- facts ---
	b.WriteString("\n## Host facts\n\n")
	b.WriteString("| Guest | distro | kernel | glibc | ModemManager | SELinux | seat | linkage |\n")
	b.WriteString("|---|---|---|---|---|---|---|---|\n")
	for _, h := range hosts {
		f := r.facts[h.Name]
		if f == nil {
			fmt.Fprintf(&b, "| %s | (not collected) | | | | | | |\n", h.Name)
			continue
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s | %s | %s |\n",
			h.Name, dash(f["distro"]), dash(f["kernel"]), dash(f["glibc"]),
			dash(f["modemmanager"]), dash(f["selinux"]), dash(f["seat"]), dash(f["linkage"]))
	}

	// --- the questions the round has to answer ---
	b.WriteString("\n## Questions this round must answer\n\n")
	b.WriteString("Automated where possible; the rest need a human with the dongle.\n\n")
	b.WriteString("| # | Question | Answer |\n|---|---|---|\n")

	static := r.staticness()
	fmt.Fprintf(&b, "| 1 | Is the musl build genuinely static everywhere? | %s |\n", static)
	fmt.Fprintf(&b, "| 2 | Does `probe` work without sudo? | %s |\n", r.probeAnswer())
	fmt.Fprintf(&b, "| 3 | Same on a headless guest (no logind seat)? | %s |\n", r.headlessAnswer(hosts))
	fmt.Fprintf(&b, "| 4 | Does ModemManager probe the 8888:cdc0 tty? | %s |\n", r.modemManagerAnswer())
	b.WriteString("| 5 | Does the hypervisor keep the device across `unlock`'s re-enumeration? | ⏳ manual |\n")
	b.WriteString("| 6 | Does `flash-cdc --execute` complete Linux-natively? (**gates ROADMAP Phase 4.1**) | ⏳ manual |\n")
	b.WriteString("| 7 | Does `--transport serial` work, and is it more reliable than libusb? | ⏳ manual |\n")
	b.WriteString("| 8 | Any distro where the TUI misrenders or leaves the terminal in raw mode? | ⏳ manual |\n")

	// --- failures in full ---
	var failures []Result
	for _, name := range r.order {
		phases := r.cells[name]
		keys := make([]string, 0, len(phases))
		for k := range phases {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			if !phases[k].OK() {
				failures = append(failures, phases[k])
			}
		}
	}
	if len(failures) > 0 {
		b.WriteString("\n## Failures\n\n")
		for _, f := range failures {
			fmt.Fprintf(&b, "### %s — %s\n\n", f.Host.Name, f.Phase)
			if f.Err != nil {
				fmt.Fprintf(&b, "transport error: `%v`\n\n", f.Err)
			}
			fmt.Fprintf(&b, "exit %d\n\n```\n%s%s```\n\n",
				f.ExitCode, tail(f.Stdout, 40), tail(f.Stderr, 20))
		}
	}

	b.WriteString("\n## Still manual\n\n")
	b.WriteString("- **P2 (unlock)** — changes device state. `staging/linux-testing/p2-usb-checks.sh`.\n")
	b.WriteString("- **P3 (flash)** — destructive, needs a known-good image and a sacrificial dongle.\n")
	b.WriteString("- **Passthrough survival** — bind the hypervisor rule to the bus/port, not the\n")
	b.WriteString("  VID:PID: `unlock` re-enumerates the dongle and an ID-keyed rule drops it\n")
	b.WriteString("  exactly when it matters (LINUX-TESTING.md §2.1).\n")

	return b.String()
}

func (r *Report) notes(h Host) string {
	var notes []string
	if h.Headless {
		notes = append(notes, "headless")
	}
	if !h.HasDongle {
		notes = append(notes, "no dongle")
	}
	if f := r.facts[h.Name]; f != nil {
		if f["mm_ignore"] == "no" && f["modemmanager"] == "active" {
			notes = append(notes, "**MM active, ignore-rules missing**")
		}
		if f["selinux"] == "Enforcing" {
			notes = append(notes, "SELinux enforcing")
		}
	}
	return strings.Join(notes, "; ")
}

func (r *Report) staticness() string {
	var dynamic []string
	seen := 0
	for host, f := range r.facts {
		switch f["linkage"] {
		case "statically linked":
			seen++
		case "dynamically linked":
			dynamic = append(dynamic, host)
		}
	}
	sort.Strings(dynamic)
	if len(dynamic) > 0 {
		return fmt.Sprintf("❌ dynamically linked on: %s", strings.Join(dynamic, ", "))
	}
	if seen == 0 {
		return "⏳ not observed"
	}
	return fmt.Sprintf("✅ static on all %d guests checked", seen)
}

func (r *Report) probeAnswer() string {
	var pass, fail []string
	for host, phases := range r.cells {
		res, ok := phases["p1"]
		if !ok {
			continue
		}
		if res.OK() {
			pass = append(pass, host)
		} else {
			fail = append(fail, host)
		}
	}
	sort.Strings(pass)
	sort.Strings(fail)
	switch {
	case len(pass) == 0 && len(fail) == 0:
		return "⏳ P1 not run (needs the dongle)"
	case len(fail) == 0:
		return fmt.Sprintf("✅ yes on %s", strings.Join(pass, ", "))
	default:
		return fmt.Sprintf("❌ failed on %s", strings.Join(fail, ", "))
	}
}

func (r *Report) headlessAnswer(hosts []Host) string {
	for _, h := range hosts {
		if !h.Headless {
			continue
		}
		res, ok := r.cells[h.Name]["p1"]
		if !ok {
			return "⏳ headless guest defined but P1 not run"
		}
		if res.OK() {
			return fmt.Sprintf("✅ yes on %s (uaccess applies without a seat)", h.Name)
		}
		return fmt.Sprintf("❌ no on %s — the plugdev fallback is needed", h.Name)
	}
	return "⏳ no headless guest in the matrix — add one (`\"headless\": true`)"
}

func (r *Report) modemManagerAnswer() string {
	// Distinguish "asked and nobody runs it" from "never asked". Reporting the former when the
	// truth is the latter would retire an open question on no evidence.
	if len(r.facts) == 0 {
		return "⏳ facts not collected — run `vmatrix facts`"
	}
	var active, missing []string
	for host, f := range r.facts {
		if f["modemmanager"] == "active" {
			active = append(active, host)
			if f["mm_ignore"] == "no" {
				missing = append(missing, host)
			}
		}
	}
	sort.Strings(active)
	sort.Strings(missing)
	if len(active) == 0 {
		return "ModemManager not active on any guest — the udev rules are defensive only"
	}
	s := fmt.Sprintf("ModemManager active on: %s.", strings.Join(active, ", "))
	if len(missing) > 0 {
		s += fmt.Sprintf(" ⚠ ignore-rules NOT installed on: %s.", strings.Join(missing, ", "))
	}
	return s + " Whether it actually probes 8888:cdc0 needs P2 (manual)."
}

func dash(s string) string {
	if s == "" {
		return "—"
	}
	return s
}

// tail keeps output blocks readable when a guest is very chatty.
func tail(s string, n int) string {
	if s == "" {
		return ""
	}
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	if len(lines) > n {
		lines = append([]string{fmt.Sprintf("… (%d earlier lines omitted)", len(lines)-n)}, lines[len(lines)-n:]...)
	}
	return strings.Join(lines, "\n") + "\n"
}
